---
language: node_js
node_js:
  - 6
  - 8
  - 9
cache:
  yarn: true
  directories:
  - node_modules
notifications:
  email: false
install:
  - yarn install
script:
  - echo $(ruby --version)
  - yarn run test
